### PR TITLE
redesign

### PR DESCRIPTION
**Pull request by GauravKukreti**
Redesigned.
remaining:
- QR Loading animation
- font styling and size
- Margin and padding

### CODE REVIEW

**Comment by JMcrafter26** [comment]
I can confirm, it also works on iPhone. 
image

**Comment by GauravKukreti** [comment]
i just remembered you need everything offline. I will work on it

**Comment by JMcrafter26** [comment]
But it's not possible to use external svg. Everything must be offline and in this one file. This is why I used gzip

**Comment by GauravKukreti** [comment]
i just remembered you need everything offline. I will work on it

**Pull request closed without merging**
