### PR TITLE
update

### PR DESCRIPTION
**Pull request by GauravKukreti**
reduced size from 31kb to 21kb
background svg loading offline

### CODE REVIEW

**Comment by JMcrafter26** [comment]
Thank you for reducing the size of the file. When this project is finished, I will run the file through minifiers, that will also reduce the size.

Because of this, it is not necessary to remove some potentially necessary lines of code.

**Comment by JMcrafter26** [comment]
How are you going to make the QR code loader? Maybe you could use my css code?
I checked the characters and if I minify this file, it would not exceed the limit. So it is still possible to add some details.

**Comment by GauravKukreti** [comment]
Okay.
Working on it.

**Comment by GauravKukreti** [comment]
Okay.
Working on it.

**Pull request closed without merging**
